#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression "Loading installation settings..."

db_name=$(ynh_app_setting_get --key=db_name)
db_user=$db_name

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_mongo_remove_db --db_user=$db_user --db_name=$db_name

yunohost service remove mongod

ynh_safe_rm "/var/lib/mongodb"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
